const sdg_colors = {
    "no poverty": "#E5243B",
    "zero hunger": "#DDA63A",
    "good health and well-being": "#4C9F38",
    "quality education": "#C5192D",
    "gender equality": "#FF3A21",
    "clean water and sanitation": "#26BDE2",
    "affordable and clean energy": "#FCC30B",
    "decent work and economic growth": "#A21942",
    "industry, innovation and infrastructure": "#FD6925",
    "reduced inequalities": "#DD1367",
    "sustainable cities and communities": "#FD9D24",
    "responsible consumption and production": "#BF8B2E",
    "climate action": "#3F7E44",
    "life below water": "#0A97D9",
    "life on land": "#56C02B",
    "peace, justice and strong institutions": "#00689D",
    "partnerships for the goals": "#19486A",
}